import type { RouteRecord } from "vite-react-ssg";
import RootLayout from "./RootLayout";
import { ToolPageLayout } from "@/components/tools/ToolPageLayout";
import Index from "../pages/Index";
import Tools from "../pages/Tools";
import NotFound from "../pages/NotFound";
import { newsLoader, newsStaticPaths, blogLoader, blogStaticPaths } from "./news-data";

// Adapt our default-export pages to vite-react-ssg's lazy ({ Component }).
const d = (imp: () => Promise<{ default: React.ComponentType }>) => () =>
  imp().then((m) => ({ Component: m.default }));

// GENERATED from src/App.tsx by scripts/_ssg_gen_routes.cjs. 205 routes.
export const routes: RouteRecord[] = [
  {
    path: "/",
    element: <RootLayout />,
    entry: "src/ssg/RootLayout.tsx",
    children: [
      { index: true, element: <Index /> },
      { path: "auth", lazy: d(() => import("../pages/Auth")) },
      { path: "profile", lazy: d(() => import("../pages/Profile")) },
      { path: "dashboard", lazy: d(() => import("../pages/Dashboard")) },
      { path: "tools", element: <Tools /> },
      { path: "tools/:categoryId", lazy: d(() => import("../pages/ToolCategory")) },
      { path: "blog", lazy: d(() => import("../pages/Blog")) },
      { path: "blog/:slug", lazy: d(() => import("../pages/BlogArticle")), loader: blogLoader, getStaticPaths: blogStaticPaths },
      { path: "news", lazy: d(() => import("../pages/News")) },
      { path: "news/:slug", lazy: d(() => import("../pages/NewsArticle")), loader: newsLoader, getStaticPaths: newsStaticPaths },
      { path: "phones", lazy: d(() => import("../pages/categories/Phones")) },
      { path: "security", lazy: d(() => import("../pages/categories/Security")) },
      { path: "productivity", lazy: d(() => import("../pages/categories/Productivity")) },
      { path: "how-to", lazy: d(() => import("../pages/categories/HowTo")) },
      { path: "ai-tech", lazy: d(() => import("../pages/categories/AITech")) },
      { path: "smart-income", lazy: d(() => import("../pages/categories/SmartIncome")) },
      { path: "make-money", lazy: d(() => import("../pages/categories/SmartIncome")) },
      { path: "deals", lazy: d(() => import("../pages/categories/SmartIncome")) },
      { path: "gaming", lazy: d(() => import("../pages/categories/Gaming")) },
      { path: "accessories", lazy: d(() => import("../pages/categories/Accessories")) },
      { path: "career-in-tech", lazy: d(() => import("../pages/categories/CareerInTech")) },
      { path: "health-tech", lazy: d(() => import("../pages/categories/HealthTech")) },
      { path: "remote-work", lazy: d(() => import("../pages/categories/RemoteWork")) },
      { path: "green-tech", lazy: d(() => import("../pages/categories/GreenTech")) },
      { path: "creepy-tech", lazy: d(() => import("../pages/CreepyTech")) },
      { path: "cyber-awareness", lazy: d(() => import("../pages/CyberAwareness")) },
      { path: "think-before-you-click", lazy: d(() => import("../pages/ThinkBeforeYouClick")) },
      { path: "scam-alerts", lazy: d(() => import("../pages/ScamAlerts")) },
      { path: "report-scam", lazy: d(() => import("../pages/ReportScam")) },
      { path: "start-here", lazy: d(() => import("../pages/StartHere")) },
      // Reviews discontinued 2026-06-21 (focus = Africa Tech News · Tools · Security).
      // Routes removed so /reviews + /reviews/* stop prerendering; nginx 301s the
      // list to /blog and 410s the old detail URLs.
      { path: "admin", lazy: d(() => import("../pages/admin/AdminDashboard")) },
      { path: "admin/news", lazy: d(() => import("../pages/admin/AdminNews")) },
      { path: "admin/articles", lazy: d(() => import("../pages/admin/AdminArticles")) },
      { path: "admin/reviews", lazy: d(() => import("../pages/admin/AdminReviews")) },
      { path: "admin/comments", lazy: d(() => import("../pages/admin/AdminComments")) },
      { path: "admin/users", lazy: d(() => import("../pages/admin/AdminUsers")) },
      { path: "admin/messages", lazy: d(() => import("../pages/admin/AdminMessages")) },
      { path: "admin/products", lazy: d(() => import("../pages/admin/AdminProducts")) },
      { path: "admin/analytics", lazy: d(() => import("../pages/admin/AdminAnalytics")) },
      { path: "admin/creepy-tech", lazy: d(() => import("../pages/admin/AdminCreepyTech")) },
      { path: "admin/cyber-awareness", lazy: d(() => import("../pages/admin/AdminCyberAwareness")) },
      { path: "admin/scam-alerts", lazy: d(() => import("../pages/admin/AdminScamAlerts")) },
      { path: "admin/daily-tips", lazy: d(() => import("../pages/admin/AdminDailyTips")) },
      { path: "admin/threat-level", lazy: d(() => import("../pages/admin/AdminThreatLevel")) },
      { path: "admin/scam-reports", lazy: d(() => import("../pages/admin/AdminScamReports")) },
      { path: "admin/tool-feedback", lazy: d(() => import("../pages/admin/AdminToolFeedback")) },
      { path: "admin/whatsapp-queue", lazy: d(() => import("../pages/admin/AdminWhatsAppQueue")) },
      { path: "arcade", lazy: d(() => import("../pages/Arcade")) },
      { path: "arcade/math-tug-of-war", lazy: d(() => import("../pages/arcade/MathTugOfWar")) },
      { path: "arcade/speed-typing-race", lazy: d(() => import("../pages/arcade/SpeedTypingRace")) },
      { path: "arcade/word-chain-battle", lazy: d(() => import("../pages/arcade/WordChainBattle")) },
      { path: "arcade/reflex-duel", lazy: d(() => import("../pages/arcade/ReflexDuel")) },
      { path: "arcade/trivia-challenge", lazy: d(() => import("../pages/arcade/TriviaChallenge")) },
      { path: "arcade/anagram-blitz", lazy: d(() => import("../pages/arcade/AnagramBlitz")) },
      { path: "arcade/wordle", lazy: d(() => import("../pages/arcade/WordleGame")) },
      { path: "arcade/word-bomb", lazy: d(() => import("../pages/arcade/WordBomb")) },
      { path: "arcade/crossword-sprint", lazy: d(() => import("../pages/arcade/CrosswordSprint")) },
      { path: "about", lazy: d(() => import("../pages/About")) },
      { path: "newsletter", lazy: d(() => import("../pages/NewsletterArchive")) },
      { path: "reading-list", lazy: d(() => import("../pages/ReadingList")) },
      { path: "privacy", lazy: d(() => import("../pages/Privacy")) },
      { path: "terms", lazy: d(() => import("../pages/Terms")) },
      { path: "cookies", lazy: d(() => import("../pages/Cookies")) },
      { path: "contact", lazy: d(() => import("../pages/Contact")) },
      { path: "disclosure", lazy: d(() => import("../pages/Disclosure")) },
      { path: "store", lazy: d(() => import("../pages/DigiStore")) },
      { path: "books/think-before-you-click", lazy: d(() => import("../pages/books/ThinkBeforeYouClick")) },
      { path: "design-demo", lazy: d(() => import("../pages/DesignDemo")) },
      {
        element: <ToolPageLayout />,
        entry: "src/components/tools/ToolPageLayout.tsx",
        children: [
          { path: "tools/password-generator", lazy: d(() => import("../pages/tools/PasswordGenerator")) },
          { path: "tools/qr-generator", lazy: d(() => import("../pages/tools/QRGenerator")) },
          { path: "tools/image-compressor", lazy: d(() => import("../pages/tools/ImageCompressor")) },
          { path: "tools/phone-comparison", lazy: d(() => import("../pages/tools/PhoneComparison")) },
          { path: "tools/password-checker", lazy: d(() => import("../pages/tools/PasswordAnalyzer")) },
          { path: "tools/upgrade-calculator", lazy: d(() => import("../pages/tools/UpgradeCalculator")) },
          { path: "tools/json-formatter", lazy: d(() => import("../pages/tools/JsonFormatter")) },
          { path: "tools/base64-encoder", lazy: d(() => import("../pages/tools/Base64Encoder")) },
          { path: "tools/color-picker", lazy: d(() => import("../pages/tools/ColorPicker")) },
          { path: "tools/lorem-ipsum", lazy: d(() => import("../pages/tools/LoremIpsum")) },
          { path: "tools/unit-converter", lazy: d(() => import("../pages/tools/UnitConverter")) },
          { path: "tools/speed-test", lazy: d(() => import("../pages/tools/SpeedTest")) },
          { path: "tools/privacy-checker", lazy: d(() => import("../pages/tools/PrivacyChecker")) },
          { path: "tools/ip-lookup", lazy: d(() => import("../pages/tools/IPLookup")) },
          { path: "tools/hash-generator", lazy: d(() => import("../pages/tools/HashGenerator")) },
          { path: "tools/url-parser", lazy: d(() => import("../pages/tools/URLParser")) },
          { path: "tools/text-counter", lazy: d(() => import("../pages/tools/TextCounter")) },
          { path: "tools/meeting-cost-calculator", lazy: d(() => import("../pages/tools/MeetingCostCalculator")) },
          { path: "tools/email-subject-tester", lazy: d(() => import("../pages/tools/EmailSubjectTester")) },
          { path: "tools/pomodoro-timer", lazy: d(() => import("../pages/tools/PomodoroTimer")) },
          { path: "tools/subscription-tracker", lazy: d(() => import("../pages/tools/SubscriptionTracker")) },
          { path: "tools/habit-tracker", lazy: d(() => import("../pages/tools/HabitTrackerV2")) },
          { path: "tools/job-tracker", lazy: d(() => import("../pages/tools/JobTracker")) },
          { path: "tools/link-in-bio", lazy: d(() => import("../pages/tools/LinkInBio")) },
          { path: "tools/invoice-generator", lazy: d(() => import("../pages/tools/InvoiceGenerator")) },
          { path: "tools/content-repurposer", lazy: d(() => import("../pages/tools/ContentRepurposer")) },
          { path: "tools/resume-builder", lazy: d(() => import("../pages/tools/ResumeBuilder")) },
          { path: "tools/url-shortener", lazy: d(() => import("../pages/tools/URLShortener")) },
          { path: "tools/creator-analytics", lazy: d(() => import("../pages/tools/CreatorAnalytics")) },
          { path: "tools/regex-tester", lazy: d(() => import("../pages/tools/RegexTester")) },
          { path: "tools/cron-builder", lazy: d(() => import("../pages/tools/CronBuilder")) },
          { path: "tools/jwt-decoder", lazy: d(() => import("../pages/tools/JWTDecoder")) },
          { path: "tools/markdown-editor", lazy: d(() => import("../pages/tools/MarkdownEditor")) },
          { path: "tools/gradient-generator", lazy: d(() => import("../pages/tools/GradientGenerator")) },
          { path: "tools/typing-test", lazy: d(() => import("../pages/tools/TypingTest")) },
          { path: "tools/salary-comparison", lazy: d(() => import("../pages/tools/SalaryComparison")) },
          { path: "tools/business-name-generator", lazy: d(() => import("../pages/tools/AIBusinessNameGenerator")) },
          { path: "tools/decision-wheel", lazy: d(() => import("../pages/tools/DecisionWheel")) },
          { path: "tools/expense-tracker", lazy: d(() => import("../pages/tools/BudgetTracker")) },
          { path: "tools/favicon-generator", lazy: d(() => import("../pages/tools/FaviconGenerator")) },
          { path: "tools/meta-tag-generator", lazy: d(() => import("../pages/tools/MetaTagGenerator")) },
          { path: "tools/contract-generator", lazy: d(() => import("../pages/tools/ContractGenerator")) },
          { path: "tools/cover-letter-generator", lazy: d(() => import("../pages/tools/CoverLetterGenerator")) },
          { path: "tools/username-generator", lazy: d(() => import("../pages/tools/UsernameGenerator")) },
          { path: "tools/screen-time-calculator", lazy: d(() => import("../pages/tools/ScreenTimeCalculator")) },
          { path: "tools/pricing-calculator", lazy: d(() => import("../pages/tools/PricingCalculator")) },
          { path: "tools/roi-calculator", lazy: d(() => import("../pages/tools/ROICalculator")) },
          { path: "tools/daily-standup", lazy: d(() => import("../pages/tools/DailyStandup")) },
          { path: "tools/time-tracker", lazy: d(() => import("../pages/tools/TimeTracker")) },
          { path: "tools/daily-journal", lazy: d(() => import("../pages/tools/DailyJournal")) },
          { path: "tools/water-tracker", lazy: d(() => import("../pages/tools/WaterTracker")) },
          { path: "tools/focus-score", lazy: d(() => import("../pages/tools/FocusScore")) },
          { path: "tools/side-hustle-calculator", lazy: d(() => import("../pages/tools/SideHustleProjector")) },
          { path: "tools/startup-validator", lazy: d(() => import("../pages/tools/AppIdeaValidator")) },
          { path: "tools/personal-brand-audit", lazy: d(() => import("../pages/tools/PersonalBrandAudit")) },
          { path: "tools/carbon-footprint", lazy: d(() => import("../pages/tools/CarbonFootprintV2")) },
          { path: "tools/career-matcher", lazy: d(() => import("../pages/tools/CareerMatcher")) },
          { path: "tools/placeholder-image", lazy: d(() => import("../pages/tools/PlaceholderImage")) },
          { path: "tools/product-description-generator", lazy: d(() => import("../pages/tools/ProductDescriptionGenerator")) },
          { path: "tools/blog-outline-generator", lazy: d(() => import("../pages/tools/BlogOutlineGenerator")) },
          { path: "tools/social-caption-generator", lazy: d(() => import("../pages/tools/SocialCaptionGenerator")) },
          { path: "tools/meeting-notes-summarizer", lazy: d(() => import("../pages/tools/MeetingNotesSummarizer")) },
          { path: "tools/ai-content-idea-generator", lazy: d(() => import("../pages/tools/AIContentIdeaGenerator")) },
          { path: "tools/ai-prompt-generator", lazy: d(() => import("../pages/tools/AIPromptImprover")) },
          { path: "tools/ai-startup-name-generator", lazy: d(() => import("../pages/tools/AIStartupNameGenerator")) },
          { path: "tools/adsense-calculator", lazy: d(() => import("../pages/tools/AdSenseCalculator")) },
          { path: "tools/bill-splitter", lazy: d(() => import("../pages/tools/BillSplitter")) },
          { path: "tools/bmi-calculator", lazy: d(() => import("../pages/tools/BmiCalculator")) },
          { path: "tools/color-palette-extractor", lazy: d(() => import("../pages/tools/ColorPaletteExtractor")) },
          { path: "tools/countdown-timer", lazy: d(() => import("../pages/tools/CountdownTimer")) },
          { path: "tools/fake-data-generator", lazy: d(() => import("../pages/tools/FakeDataGenerator")) },
          { path: "tools/file-converter", lazy: d(() => import("../pages/tools/FileConverter")) },
          { path: "tools/freelance-rate-calculator", lazy: d(() => import("../pages/tools/FreelanceRateCalculator")) },
          { path: "tools/image-converter", lazy: d(() => import("../pages/tools/ImageConverter")) },
          { path: "tools/meme-generator", lazy: d(() => import("../pages/tools/MemeGenerator")) },
          { path: "tools/mortgage-calculator", lazy: d(() => import("../pages/tools/LoanCalculator")) },
          { path: "tools/startup-cost-calculator", lazy: d(() => import("../pages/tools/StartupCostCalculator")) },
          { path: "tools/text-to-speech", lazy: d(() => import("../pages/tools/TextToSpeech")) },
          { path: "tools/world-clock", lazy: d(() => import("../pages/tools/WorldClock")) },
          // youtube-thumbnail-downloader removed (AdSense policy: copyrighted-asset
          // download / targeting Google's own property). 301'd to thumbnail-tester in nginx.
          { path: "tools/currency-converter", lazy: d(() => import("../pages/tools/CurrencyConverter")) },
          { path: "tools/hook-generator", lazy: d(() => import("../pages/tools/HookGenerator")) },
          { path: "tools/idea-parking-lot", lazy: d(() => import("../pages/tools/IdeaParkingLot")) },
          { path: "tools/savings-goal-visualizer", lazy: d(() => import("../pages/tools/SavingsGoalVisualizer")) },
          { path: "tools/paycheck-calculator", lazy: d(() => import("../pages/tools/PaycheckCalculator")) },
          { path: "tools/thumbnail-tester", lazy: d(() => import("../pages/tools/ThumbnailTester")) },
          { path: "tools/hashtag-analyzer", lazy: d(() => import("../pages/tools/HashtagAnalyzer")) },
          { path: "tools/loan-emi-calculator", lazy: d(() => import("../pages/tools/LoanEmiCalculator")) },
          { path: "tools/net-worth-tracker", lazy: d(() => import("../pages/tools/NetWorthTracker")) },
          { path: "tools/compatibility-calculator", lazy: d(() => import("../pages/tools/CompatibilityCalculator")) },
          { path: "tools/tech-trivia-generator", lazy: d(() => import("../pages/tools/TechTriviaGenerator")) },
          { path: "tools/sitting-time-calculator", lazy: d(() => import("../pages/tools/SittingTimeCalculator")) },
          { path: "tools/math-tug-of-war", lazy: d(() => import("../pages/tools/MathTugOfWar")) },
          { path: "tools/decision-matrix", lazy: d(() => import("../pages/tools/DecisionMatrix")) },
          { path: "tools/project-timeline", lazy: d(() => import("../pages/tools/ProjectTimeline")) },
          { path: "tools/compound-interest", lazy: d(() => import("../pages/tools/CompoundInterest")) },
          { path: "tools/fire-calculator", lazy: d(() => import("../pages/tools/FIRECalculator")) },
          { path: "tools/cost-of-living", lazy: d(() => import("../pages/tools/CostOfLiving")) },
          { path: "tools/ghana-tax-calculator", lazy: d(() => import("../pages/tools/GhanaTaxCalculator")) },
          { path: "tools/cyber-risk-scorecard", lazy: d(() => import("../pages/tools/CyberRiskScorecard")) },
          { path: "tools/tech-stack-recommender", lazy: d(() => import("../pages/tools/TechStackRecommender")) },
          { path: "tools/viral-post-analyzer", lazy: d(() => import("../pages/tools/ViralPostAnalyzer")) },
          { path: "tools/resume-roaster", lazy: d(() => import("../pages/tools/ResumeRoaster")) },
          { path: "tools/youtube-title-optimizer", lazy: d(() => import("../pages/tools/YouTubeTitleOptimizer")) },
          { path: "tools/concept-explainer", lazy: d(() => import("../pages/tools/ConceptExplainer")) },
          { path: "tools/seo-auditor", lazy: d(() => import("../pages/tools/BlogSEOAuditor")) },
          { path: "tools/rent-vs-buy", lazy: d(() => import("../pages/tools/RentVsBuy")) },
          { path: "tools/couples-finance", lazy: d(() => import("../pages/tools/CouplesFinance")) },
          { path: "tools/pay-yourself-first", lazy: d(() => import("../pages/tools/PayYourselfFirst")) },
          { path: "tools/variable-income-budget", lazy: d(() => import("../pages/tools/VariableIncomeBudget")) },
          { path: "tools/brain-dump", lazy: d(() => import("../pages/tools/BrainDumpOutline")) },
          { path: "tools/hook-scorer", lazy: d(() => import("../pages/tools/HookScorer")) },
          { path: "tools/content-calendar", lazy: d(() => import("../pages/tools/ContentCalendar")) },
          { path: "tools/brand-pitch", lazy: d(() => import("../pages/tools/BrandPitchGenerator")) },
          { path: "tools/farm-calculator", lazy: d(() => import("../pages/tools/FarmInputCalculator")) },
          { path: "tools/stock-alert", lazy: d(() => import("../pages/tools/StockAlertTool")) },
          { path: "tools/creator-monetization", lazy: d(() => import("../pages/tools/CreatorMonetization")) },
          { path: "tools/nutrition-analyzer", lazy: d(() => import("../pages/tools/MealNutritionAnalyzer")) },
          { path: "tools/startup-readiness", lazy: d(() => import("../pages/tools/StartupReadiness")) },
          { path: "tools/business-registration", lazy: d(() => import("../pages/tools/BusinessRegGuide")) },
          { path: "tools/statistics-visualizer", lazy: d(() => import("../pages/tools/StatisticsVisualizer")) },
          { path: "tools/phishing-quiz", lazy: d(() => import("../pages/tools/PhishingQuiz")) },
          { path: "tools/whatsapp-audit", lazy: d(() => import("../pages/tools/WhatsAppAudit")) },
          { path: "tools/scam-analyzer", lazy: d(() => import("../pages/tools/ScamAnalyzer")) },
          { path: "tools/incident-response", lazy: d(() => import("../pages/tools/IncidentResponse")) },
          { path: "tools/password-strength", lazy: d(() => import("../pages/tools/PasswordStrength")) },
          { path: "tools/wifi-qr-generator", lazy: d(() => import("../pages/tools/WifiQrGenerator")) },
          { path: "tools/this-day-in-history", lazy: d(() => import("../pages/tools/ThisDayInHistory")) },
          { path: "tools/life-progress-bar", lazy: d(() => import("../pages/tools/LifeProgressBar")) },
          { path: "tools/cybersecurity-playbook", lazy: d(() => import("../pages/tools/CybersecurityPlaybook")) },
          { path: "tools/momo-fee-calculator", lazy: d(() => import("../pages/tools/MoMoFeeCalculator")) },
          { path: "tools/ghana-electricity-calculator", lazy: d(() => import("../pages/tools/GhanaElectricityCalculator")) },
          { path: "tools/ghana-scam-checker", lazy: d(() => import("../pages/tools/GhanaScamChecker")) },
          { path: "tools/ghs-exchange-rate", lazy: d(() => import("../pages/tools/GhsExchangeRate")) },
        ],
      },
      { path: "*", element: <NotFound /> },
    ],
  },
];
